#! /bin/sh

### Legal
#
# Author:  Thomas Debesse <dev@illwieckz.net>
# License: ISC
# 

getDirs () {
	find . -maxdepth 1 -type d | tail -n +2
}

zipDir () {
	base="$(echo "${1}" | sed -e 's#/*$##')"
	7z -tzip -mx=9 -mfb=258 -mpass=15 a "${base}.zip" "${base}"
}

if [ -z ${@} ]
then
	for dir in $(getDirs)
	do
		zipDir "${dir}"
	done
else
	for dir in ${@}
	do
		zipDir "${dir}"
	done
fi

#EOF
